app/models.py
from app import db, login
from flask_login import UserMixin 
from datetime import datetime as dt
from werkzeug.security import generate_password_hash, check_password_hash

class Cart(db.Model):
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), primary_key=True)
    item_id = db.Column(db.Integer, db.ForeignKey('item.id'), primary_key=True)
    

    def save(self):
        db.session.add(self)
        db.session.commit()

    def delete(self):
        db.session.delete(self)
        db.session.commit()

class User(UserMixin, db.Model):
    __tablename__ = 'user'
    id = db.Column(db.Integer, primary_key=True)
    first_name = db.Column(db.String(150))
    last_name = db.Column(db.String(150))
    email = db.Column(db.String(150), unique=True)
    password = db.Column(db.String(200))
    created_on = db.Column(db.DateTime, default = dt.utcnow)
    admin = db.Column(db.Boolean, default=False)
    user_item = db.relationship(
        'Item',
        secondary = 'cart',
        backref= 'users',        
        lazy='dynamic'
    )

    def __repr__(self):
        return f'<User: {self.id} | {self.email}>'

    def hash_password(self, original_password):
        return generate_password_hash(original_password)
    
    def check_hashed_password(self, login_password):
        return check_password_hash(self.password, login_password)

    def from_dict(self, data):
        self.first_name = data['first_name']
        self.last_name = data['last_name']
        self.email = data['email']
        self.password = self.hash_password(data['password'])

    def total_items(self):
        pass

    def total_price(self):
        pass
       
    def save(self):
        db.session.add(self)
        db.session.commit() 

@login.user_loader
def load_user(id):
    return User.query.get(int(id))

class Item(db.Model):
    __tablename__ = 'item'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(50))
    price = db.Column(db.Integer)
    desc = db.Column(db.Text)
    img = db.Column(db.String)
    category = db.Column(db.String)
    created_on = db.Column(db.DateTime, index=True, default=dt.utcnow)
    

    def __repr__ (self):
        return f'<Item: {self.id} | {self.name}>'

    def to_dict(self):
        data={
            'id':self.id ,
            'name':self.name ,
            'desc':self.desc ,
            'price':self.price ,
            'img':self.img ,
            'category':self.category ,
            'created_on':self.created_on ,       
        }
        return data

    def from_dict(self, data):
        for field in ["name", "desc", "price", "img", "category"]:
            if field in data:
                setattr(self,field, data[field])

    def save(self):
        db.session.add(self)
        db.session.commit()

    def delete(self):
        db.session.delete(self)
        db.session.commit()

app/blueprints/api/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, IntegerField
from wtforms.validators import DataRequired, Email, EqualTo, ValidationError
from ...models import User

class ItemForm(FlaskForm):
    name = StringField('Name', validators=[DataRequired()])
    price = IntegerField('Price', validators=[DataRequired()])
    desc = StringField('Description', validators=[DataRequired()])
    img = StringField('Image', validators=[DataRequired()])
    category = StringField('Category', validators=[DataRequired()])
    submit = SubmitField('Create Item')

app/blueprints/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField
from wtforms.validators import DataRequired

app/__init__.py
from flask import Flask
from config import Config
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from flask_login import LoginManager

login= LoginManager()
db = SQLAlchemy()
migrate = Migrate()

def create_app(config_class=Config):
    app = Flask(__name__)
    app.config.from_object(config_class)

    login.init_app(app)
    db.init_app(app)
    migrate.init_app(app, db)
    
    login.login_view='auth.login'
    login.login_message = "Please login to access the Fancy Things Shop."
    login.login_message_category='success'

    from .blueprints.auth import bp as auth_bp
    app.register_blueprint(auth_bp)

    from .blueprints.main import bp as main_bp
    app.register_blueprint(main_bp)

    from .blueprints.api import bp as api_bp
    app.register_blueprint(api_bp)

    return app

app/blueprints/api/__init__.py
from flask import Blueprint

bp = Blueprint('api',__name__,url_prefix='/api')

from .import routes 

app/blueprints/api/routes.py
from . import bp as api
from.forms import ItemForm
from app.blueprints.auth.auth import token_auth
from flask import request, make_response, g, abort
from flask import render_template, request, flash, redirect, url_for
from app.models import Item, Cart, User, db
from flask_login import current_user, login_required

@api.route('/create_item', methods = ['GET', 'POST'])

def create_item():
    form = ItemForm()
    if request.method == 'POST' and form.validate_on_submit():
        try:
            new_item_data = {
                "name":form.name.data.title(),
                "price":form.price.data,
                "desc":form.desc.data,
                "img":form.img.data,
                "category":form.category.data,
            }
            new_item_object = Item()
    
            new_item_object.from_dict(new_item_data)
            
            new_item_object.save()
        except:
            flash('There was an unexpected error. Please Try Again', 'danger')
            return render_template('additem.html.j2', form=form)
        flash('You have successfully created the item', 'warning')
        return redirect(url_for('api.view_shop'))
    
    return render_template('additem.html.j2', form = form)

@api.route('/view_shop', methods=['GET'])
@login_required
def view_shop():
    items = Item.query.all()
    return render_template('view_shop.html.j2', items = items)

@api.route('/clothes', methods=['GET'])
@login_required
def shop_clothes():
    items = Item.query.filter_by(category = 'clothes').all()
    return render_template('view_shop.html.j2', items = items)

@api.route('/valuables', methods=['GET'])
@login_required
def shop_valuables():
    items = Item.query.filter_by(category = 'valuables').all()
    return render_template('view_shop.html.j2', items = items)

@api.route('/accessories', methods=['GET'])
@login_required
def shop_accessories():
    items = Item.query.filter_by(category = 'accessories').all()
    return render_template('view_shop.html.j2', items = items)

@api.route('/add_to_cart/<int:id>')
@login_required
def add_to_cart(id):
    item = Item.query.get((id))    
    current_user.user_item.append(item)
    db.session.commit()
    flash(f'You have added {item.name} to the cart', 'success')
    return redirect(url_for('api.view_shop'))

@api.route('/remove_from_cart/<int:id>')
@login_required
def remove_from_cart(id):
    item = Item.query.get((id))
    print(item)
    current_user.user_item.remove(item)
    db.session.commit()
    flash(f'You have removed this from your cart', 'success')
    return redirect(url_for('api.cart'))

@api.route('/remove_all_items')
@login_required
def remove_all_items():    
    items = Cart.query.filter_by(user_id = current_user.id).all()
    for item in items:
        print(item)
        Cart.delete(item)
    db.session.commit()
    flash(f'You have cleared your cart', 'danger')
    return redirect(url_for('api.cart'))

@api.route('/cart', methods=['GET'])
@login_required
def cart(): 
    items = current_user.user_item
    return render_template('cart.html.j2', items = items)

@api.route('/item/<int:id>')
@login_required
def get_item(id):
    item = Item.query.get(id)
    return render_template('single_item.html.j2', item=item)

app/blueprints/main/__init__.py
from flask import Blueprint

bp = Blueprint('main',__name__,url_prefix='')

from .import routes

app/blueprints/main/routes.py
from .import bp as main 
from app.models import Item
from flask import render_template, request, flash, redirect, url_for
import requests
from flask_login import  login_required, current_user

@main.route('/', methods=['GET'])
@login_required
def index():
    return render_template('index.html.j2')

app/templates/accessories.html.j2
{% extends 'base.html.j2' %}

{% block title %}
    Fancy Things
{% endblock %}

    {% block shop_nav %}
         {% include './includes/shopcat.html.j2'%}
    {% endblock %}

{% block content %}

    <div id="box_container" class="d-flex flex-wrap">
    {% if items %}
    {% for item in items %}
    
    <div id="box" class="d-flex flex-wrap mx-2" >
        <div id="item-card" class="card col-3 mx-auto" style="width: 18rem;" >
            <div id="card" class="row g-0">
                <div class="col-md-4">
                    
                </div>
            <div class="col-md-12" style="height: 32vh">
            <div class="card-body">
                <img src="{{item.img}}" class="card-img-top" alt="Item Image" style="height: 15vh">
                <h5 class="card-title">{{item.name}}</h5>
                <p class="card-text">
                
                    <ul>
                         
                        <li><small><a href="{{url_for('api.get_item', id=item.id)}}">View Description</a></small> </li>    
                        
                        <div>Price: ${{item.price}}</div>
                        
                                               
                    </ul>
                </p>
                
            <button id="button" type="button" class="card-button" onclick="location.href='{{url_for('api.add_to_cart', id=item.id)}}'">
                Add To Cart
            </button>
            </div>
            </div>
        </div>
    </div>
    </div>
        {% endfor %}
    {% endif %}

{% endblock %}

app/templates/additem.html.j2
{% extends 'base.html.j2' %}

{% block title %}
    Add To Store
{% endblock %}

{% block css%}
    <link href="{{url_for('static',filename='css/login.css')}}" rel="stylesheet">
    {% endblock%}

{% block content %}
<br>
    <h1>Add Item To Store</h1>
    <form action="{{url_for('api.create_item')}}" method='POST'>
        {{ form.hidden_tag() }}

        <div>
            {{form.name.label(class="form-label")}}
            {{form.name(class="form-control")}}
        </div>
        <div>
            {{form.desc.label(class="form-label")}}
            {{form.desc(class="form-control")}}
        </div>
        <div>
            {{form.price.label(class="form-label")}}
            {{form.price(class="form-control")}}
            
        </div>
        <div>
            {{form.img.label(class="form-label")}}
            {{form.img(class="form-control")}}
        </div>
        <div>
            {{form.category.label(class="form-label")}}
            {{form.category(class="form-control")}}
        </div>
        <br>
        <div>
        {{form.submit(class="bt btn-success form-control")}}
        </div>

    </form>

{% endblock %}

app/templates/base.html.j2
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}
        
    {% endblock %}</title>
    
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
   <link href="{{url_for('static',filename='css/main.css')}}" rel="stylesheet">
    {% block css%}
    
    {% endblock%}   
  <link rel="icon" href="{{ url_for('static',filename='images/favicon.ico')}}">
</head>
<body>

    {% include './includes/nav.html.j2'%}
    {% with messages = get_flashed_messages(with_categories=true)%}
  {% if messages %}
    {% for class, message in messages %}
      <div class="alert alert-{{class}} alert-dismissible fade show" role="alert">
        {{message}}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
    {% endfor %}
  {% endif %}
{% endwith %}
{% block content_title %}

          {% endblock %}
  {% block shop_nav %}
  {% endblock %}

      <div class="container">
          {% block content %}

          {% endblock %}
          
      </div>

      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</body>
</html>

app/templates/cart.html.j2
{% extends 'base.html.j2' %}

{% block title %}
    Main Page
{% endblock %}

{% block css%}
    <link href="{{url_for('static',filename='css/login.css')}}" rel="stylesheet">
    {% endblock%}

{% block content_title %}

<br>
  <h1>My Cart</h1>
  <br> 
 
 <div class="d-flex justify-content-center">
    
    <br>
    <button id="button" type="button" class="card-button" onclick="location.href='{{url_for('api.remove_all_items')}}'">
                Remove All Items From Cart
            </button>
    </div>
   
{% endblock %}

{% block content %}
   <div id="box_container" class="d-flex flex-row">
    {% if items %}

    {% for item in items %}

    <div id="box" class="d-flex flex-row mx-2" >
        <div id="item-card" class="card col-3 mx-auto" style="width: 18rem;" >
            <div id="card" class="row g-0">
                <div class="col-md-4">
                    
                </div>
            <div class="col-md-12" style="height: 32vh">
            <div class="card-body">
                <img src="{{item.img}}" class="card-img-top" alt="Item Image" style="height: 15vh">
                <h5 class="card-title">{{item.name}}</h5>
                <p class="card-text">

                    <ul>
                        <li><small><a href="{{url_for('api.get_item', id=item.id)}}">View Description</a> </li>    
                        
                        <div>Price: ${{item.price}}</div>                        
                    </ul>
                </p>
                
            <button id="button" type="button" class="card-button" onclick="location.href='{{url_for('api.remove_from_cart', id=item.id)}}'">
                Remove From Cart
            </button>
            </div>
            </div>
        </div>
    </div>
    </div>
        {% endfor %}
    {% endif %}
{% endblock %}

app/templates/clothes.html.j2
{% extends 'base.html.j2' %}

{% block title %}
    Fancy Things
{% endblock %}

    {% block shop_nav %}
        {% include './includes/shopcat.html.j2'%}
    {% endblock %}

{% block content %}

    <div id="box_container" class="d-flex flex-wrap">
    {% if items %}
    {% for item in items %}
    
    
    <div id="box" class="d-flex flex-wrap mx-2" >
        <div id="item-card" class="card col-3 mx-auto" style="width: 18rem;" >
            <div id="card" class="row g-0">
                <div class="col-md-4">
                    
                </div>
            <div class="col-md-12" style="height: 32vh">
            <div class="card-body">
                <img src="{{item.img}}" class="card-img-top" alt="Item Image" style="height: 15vh">
                <h5 class="card-title">{{item.name}}</h5>
                <p class="card-text">
                
                    <ul>
                         
                        <li><small><a href="{{url_for('api.get_item', id=item.id)}}">View Description</a></small> </li>    
                        
                        <div>Price: ${{item.price}}</div>
                        
                                               
                    </ul>
                </p>
                
            <button id="button" type="button" class="card-button" onclick="location.href='{{url_for('api.add_to_cart', id=item.id)}}'">
                Add To Cart
            </button>
            </div>
            </div>
        </div>
    </div>
    </div>
        {% endfor %}
    {% endif %}

{% endblock %}

app/templates/includes/card.html.j2
<div id="card" class="card col-3 mx-auto" style="width: 18rem;">
  <img src="{{item.img}}" class="card-img-top" alt="Item Image">
  <div class="card-body">
    <h5 class="card-title"  STYLE="text-transform:capitalize">{{item.name}}</h5>
    <p class="card-text">
         <ul>
      
      <li>{{item.desc}}</li>
      <li>Price: ${{item.price}}</li>
    </ul>
    </p>
  </div>
  <br>
  </div>

app/templates/includes/nav.html.j2
<nav class="navbar navbar-expand-lg my-nav">
        <div class="container-fluid">
          <a class="navbar-brand" href="{{url_for('main.index')}}">Fancy Things Shop</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            {% if current_user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link" aria-current="page" href="{{url_for('main.index')}}">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{{url_for('api.view_shop')}}">Items</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{{url_for('api.cart')}}">Cart</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{{url_for('auth.user_profile')}}">Profile</a>
              </li>
              {% if current_user.admin %}
              <li class="nav-item">
                <a class="nav-link" href="{{url_for('api.create_item')}}">Create Item</a>
              </li>
            {% endif %}
              <li class="nav-item">
                <a class="nav-link" href="{{url_for('auth.logout')}}">Logout</a>
              </li>
              {% else %}
              <li class="nav-item">
                <a class="nav-link" href="{{url_for('auth.login')}}">Login</a>
              </li>
            {% endif %}
            </ul>
          </div>
        </div>
      </nav>

app/templates/includes/shopcat.html.j2
<link href="{{url_for('static',filename='css/shopcat.css')}}" rel="stylesheet">

<ul class="nav justify-content-center">
    <li>_</li>
  <li class="nav-item">
    <a class="nav-item nav-link text-white" href="{{url_for('api.view_shop')}}">All Items</a>
  </li>
  <li>_</li>
  <li class="nav-item">
    <a class="nav-item nav-link text-white" href="{{url_for('api.shop_clothes')}}">Clothes</a>
  </li>
    <li>_</li>
  <li class="nav-item">
    <a class="nav-item nav-link text-white" href="{{url_for('api.shop_valuables')}}">Valuables</a>
  </li>
  <li>_</li>
  <li class="nav-item">
    <a class="nav-item nav-link text-white" href="{{url_for('api.shop_accessories')}}">Accessories</a>
  </li>
  <li class="nav-item">_</li>
</ul>

app/templates/index.html.j2
{% extends 'base.html.j2' %}

{% block title %}
    Fancy Things Home
{% endblock %}

{% block css%}
    <link href="{{url_for('static',filename='css/index.css')}}" rel="stylesheet">
    {% endblock%}

{% block content %}
<br>
  <h1>Fancy Things Shop</h1>
  <br> 
  <p>Here at the Fancy Things Shop, we pride ourselfs in carrying only the best of goods. Our online shop is a one of a kind experience where you will be able to buy items you could not obtain anywhere else.</p>
  <br>
  <p>*****ALL SALES FINAL*****</p>
{% endblock %}

app/templates/login.html.j2
{% extends 'base.html.j2' %}

{% block title %}
    Login
{% endblock %}

{% block css%}
    <link href="{{url_for('static',filename='css/login.css')}}" rel="stylesheet">
    {% endblock%}

{% block content %}
    <h1>Login</h1>


    <form action="{{url_for('auth.login')}}" method="POST">
        {{ form.hidden_tag() }}
        <div>
            {{form.email.label(class="form-label")}}
            {{form.email(class="form-control")}}
            {% for error in form.email.errors %}
                <small style="color:red;">{{error}}</small>
            {% endfor %}

        </div>
        <br>
        <div>
            {{form.password.label(class="form-label")}}
            {{form.password(class="form-control")}}
            {% for error in form.password.errors %}
                <small style="color:red;">{{error}}</small>
            {% endfor %}

        </div>
        <br>
        <div>
        {{form.submit(class="bt btn-dark form-control")}}
        </div>
            <small style="color:primary;">{{error}}</small>
    </form>
    <br>
    <div class="d-grid gap-2">
        <a class="btn btn-dark" href="{{url_for('auth.register')}}" role="Register">Register</a>
        
        </div>
{% endblock %}

app/templates/register.html.j2
{% extends 'base.html.j2' %}

{% block title %}
    Register
{% endblock %}

{% block css%}
    <link href="{{url_for('static',filename='css/register.css')}}" rel="stylesheet">
    {% endblock%}

{% block content %}
    <h1>Register</h1>
    <form action="{{url_for('auth.register')}}" method='POST'>
        {{ form.hidden_tag() }}

        <div>
            {{form.first_name.label(class="form-label")}}
            {{form.first_name(class="form-control")}}
        </div>

        <div>
            {{form.last_name.label(class="form-label")}}
            {{form.last_name(class="form-control")}}
        </div>

        <div>
            {{form.email.label(class="form-label")}}
            {{form.email(class="form-control")}}
            {% for error in form.email.errors%}
                <small style="color:red;">{{error}}</small><br>
            {% endfor %}
        </div>

        <div>
            {{form.password.label(class="form-label")}}
            {{form.password(class="form-control")}}
        </div>

        <div>
            {{form.confirm_password.label(class="form-label")}}
            {{form.confirm_password(class="form-control")}}
            {% for error in form.confirm_password.errors%}   
                <small style="color:red;">{{error}}</small><br>
            {% endfor %}          
        </div>
        <br>
        <div>
        {{form.submit(class="bt btn-dark form-control")}}
        </div>

    </form>


{% endblock %}

app/templates/single_item.html.j2
{% extends 'base.html.j2' %}

{% block title %}
    Single Item
{% endblock %}

{% block css%}
    <link href="{{url_for('static',filename='css/single_item.css')}}" rel="stylesheet">
    {% endblock%}

{% block content %}

     <div id="box_container" class="d-flex flex-wrap justify-content-center">
    {% if item %}
    
    <div id="box" class="d-flex flex-wrap mx-2 mt-5" >
        <div id="item-card" class="card mx-auto" style="width: 18rem;" >
            <div id="card" class="row g-0">
                <div class="col-md-4">
                    
                </div>
            <div class="col-md-12" style="height: 100%">
            <div class="card-body">
                <img src="{{item.img}}" class="card-img-top" alt="Item Image" style="height: 15vh">
                <h5 class="card-title">{{item.name}}</h5>
                <p class="card-text">
                      
                        <p>{{item.desc}}</p>    
                        
                        <div>Price: ${{item.price}}</div>
                          
                </p>
                 </div>
            </div>
        </div>
    </div>
    </div>
    </div>
                
                {% endif %}


{% endblock %}

app/templates/user_profile.html.j2
{% extends 'base.html.j2' %}
{% block title %}
    Profile
{% endblock %}

{% block css%}
    <link href="{{url_for('static',filename='css/login.css')}}" rel="stylesheet">
    {% endblock%}

{% block content %}

    <h1>{{current_user.first_name}}'s Profile</h1>
    <br>
    <h2>Edit Profile</h2>
    <form action="{{url_for('auth.user_profile')}}" method='POST'>
        {{ form.hidden_tag() }}

        <div>
            {{form.first_name.label(class="form-label")}}
            {{form.first_name(class="form-control", value=current_user.first_name)}}
        </div>

        <div>
            {{form.last_name.label(class="form-label")}}
            {{form.last_name(class="form-control", value=current_user.last_name)}}
        </div>

        <div>
            {{form.email.label(class="form-label")}}
            {{form.email(class="form-control", value=current_user.email)}}
            {% for error in form.email.errors%}
                <small style="color:red;">{{error}}</small><br>
            {% endfor %}
        </div>

        <div>
            {{form.password.label(class="form-label")}}
            {{form.password(class="form-control")}}
        </div>

        <div>
            {{form.confirm_password.label(class="form-label")}}
            {{form.confirm_password(class="form-control")}}
            {% for error in form.confirm_password.errors%}   
                <small style="color:red;">{{error}}</small><br>
            {% endfor %}          
        </div>
        <br>
        <div>
        {{form.submit(class="bt btn-danger form-control")}}
        <br>
        </div>

    </form>

{% endblock %}

app/templates/valuables.html.j2
{% extends 'base.html.j2' %}

{% block title %}
    Fancy Things
{% endblock %}

    {% block shop_nav %}
        {% include './includes/shopcat.html.j2'%}
    {% endblock %}

{% block content %}

    <div id="box_container" class="d-flex flex-wrap">
    {% if items %}
    {% for item in items %}
    
    
    <div id="box" class="d-flex flex-wrap mx-2" >
        <div id="item-card" class="card col-3 mx-auto" style="width: 18rem;" >
            <div id="card" class="row g-0">
                <div class="col-md-4">
                    
                </div>
            <div class="col-md-12" style="height: 32vh">
            <div class="card-body">
                <img src="{{item.img}}" class="card-img-top" alt="Item Image" style="height: 15vh">
                <h5 class="card-title">{{item.name}}</h5>
                <p class="card-text">
                  
                    <ul>
                         
                        <li><small><a href="{{url_for('api.get_item', id=item.id)}}">View Description</a></small> </li>    
                        
                        <div>Price: ${{item.price}}</div>
                        
                                               
                    </ul>
                </p>
                
            <button id="button" type="button" class="card-button" onclick="location.href='{{url_for('api.add_to_cart', id=item.id)}}'">
                Add To Cart
            </button>
            </div>
            </div>
        </div>
    </div>
    </div>
        {% endfor %}
    {% endif %}

{% endblock %}

app/templates/view_shop.html.j2
{% extends 'base.html.j2' %}

{% block title %}
    Fancy Things
{% endblock %}

{% block css%}
    <link href="{{url_for('static',filename='css/view_shop.css')}}" rel="stylesheet">
    {% endblock%}

    {% block shop_nav %}
        {% include './includes/shopcat.html.j2'%}
    {% endblock %}


{% block content %}

    <div id="box_container" class="d-flex flex-wrap">
    {% if items %}
    {% for item in items %}
    
    
    <div id="box" class="d-flex flex-wrap mx-2" >
        <div id="item-card" class="card col-3 mx-auto" style="width: 18rem;" >
            <div id="card" class="row g-0">
                <div class="col-md-4">
                    
                </div>
            <div class="col-md-12" style="height: 32vh">
            <div class="card-body">
                <img src="{{item.img}}" class="card-img-top" alt="Item Image" style="height: 15vh">
                <h5 class="card-title">{{item.name}}</h5>
                <p class="card-text">
                
                    <ul>
                         
                        <li><small><a href="{{url_for('api.get_item', id=item.id)}}">View Description</a></small> </li>    
                        
                        <div>Price: ${{item.price}}</div>
                        
                                               
                    </ul>
                </p>
                
            <button id="button" type="button" class="card-button" onclick="location.href='{{url_for('api.add_to_cart', id=item.id)}}'">
                Add To Cart
            </button>
            </div>
            </div>
        </div>
    </div>
    </div>
        {% endfor %}
    {% endif %}

{% endblock %}